<?php
require_once __DIR__ . '/course-card-data.php';
function je_course_pages(): array
{
    $pages = [
        'java-full-stack' => [
            'slug' => 'java-full-stack-course-jaipur.php',
            'title' => 'Java Full Stack Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn Java Full Stack in Jaipur with Core Java, Spring Boot, REST APIs, Hibernate, MySQL, frontend integration and project-based training.',
            'category' => 'Full Stack Development',
            'kicker' => 'Java, Spring Boot and REST API Training',
            'h1' => 'Java Full Stack Course in Jaipur',
            'lead' => 'Build Java web applications with Core Java, Spring Boot, REST APIs, Hibernate, MySQL and frontend integration.',
            'image' => 'assets/images/courses/home14/2.jpg',
            'icon' => 'fa-leaf',
            'chips' => ['Core Java', 'Spring Boot', 'REST APIs', 'Hibernate', 'MySQL'],
            'modules' => ['Core Java foundations', 'OOP, collections and exceptions', 'JDBC and SQL', 'Servlet/JSP web flow', 'Spring and Spring Boot', 'Hibernate and JPA', 'REST API development', 'Project and interview preparation'],
            'projects' => ['Student management system', 'E-commerce API backend', 'Job portal workflow', 'Final Java full stack project'],
            'roles' => ['Java Developer', 'Spring Boot Developer', 'Backend Developer', 'Full Stack Developer'],
        ],
        'full-stack-development' => [
            'slug' => 'full-stack-development-course-jaipur.php',
            'title' => 'Full Stack Developer Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn full stack development in Jaipur with HTML, CSS, JavaScript, React, Node.js, REST APIs, SQL, MongoDB, Git, deployment and portfolio projects.',
            'category' => 'Full Stack Development',
            'kicker' => 'React, Node.js, APIs, Databases and Deployment',
            'h1' => 'Full Stack Developer Course in Jaipur',
            'lead' => 'Build complete web applications from responsive frontend interfaces to backend APIs, databases, authentication and deployment through structured practical work.',
            'image' => 'assets/images/courses/home14/1.jpg',
            'icon' => 'fa-code',
            'chips' => ['HTML & CSS', 'JavaScript', 'React.js', 'Node.js', 'REST APIs', 'SQL / MongoDB', 'Git / GitHub', 'Deployment'],
            'modules' => [
                'HTML5, CSS3, responsive UI, accessibility and browser DevTools',
                'JavaScript ES6+, DOM, forms, async programming and API consumption',
                'React components, props, state, hooks, routing and reusable UI patterns',
                'Node.js runtime, modules, Express-style routing and middleware',
                'REST API design, JSON, validation, authentication and error handling',
                'SQL queries, relational modelling, MongoDB concepts and CRUD workflows',
                'Full frontend-backend-database integration with environment configuration',
                'Git, GitHub, branching, documentation and collaborative development workflow',
                'Deployment, logging, debugging, testing checklists and production basics',
                'Portfolio packaging, technical interview practice and project explanation'
            ],
            'projects' => [
                'Responsive service portal with forms and API integration',
                'Authenticated CRUD admin dashboard with database persistence',
                'E-commerce or booking workflow with users, products and transactions',
                'API-driven analytics dashboard with loading and error states',
                'Final deployed full stack capstone with GitHub documentation'
            ],
            'roles' => ['Junior Full Stack Developer', 'Frontend / React Developer', 'Node.js Backend Developer', 'Web Application Developer'],
            'faq' => [
                ['Is this Full Stack Developer course suitable for beginners?', 'Yes. The learning path starts with web and JavaScript foundations before moving into React, backend APIs, databases and deployment.'],
                ['Which technologies are covered?', 'The core path covers HTML, CSS, JavaScript, React, Node.js, REST APIs, SQL, MongoDB concepts, Git/GitHub and deployment-oriented workflows.'],
                ['Does the course include live or portfolio projects?', 'The page is structured around practical project workflows including frontend/API integration, database-backed CRUD applications and a final capstone.'],
                ['Will I learn both SQL and NoSQL databases?', 'The curriculum introduces relational data and SQL along with MongoDB-style document database concepts so learners understand both common approaches.'],
                ['Does the course include GitHub and deployment?', 'Yes. Git/GitHub workflow, documentation, environment configuration and deployment basics are included in the learning path.'],
                ['What should I have in my portfolio before applying for developer roles?', 'Aim to present a few working, documented projects that show increasing complexity, clear Git history, database integration, APIs and a deployed demonstration where possible.']
            ],
        ],
        'python-programming' => [
            'slug' => 'python-programming-course-jaipur.php',
            'title' => 'Python Programming Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn Python Programming in Jaipur from basics to practical coding, functions, files, OOP, modules, database basics and mini projects.',
            'category' => 'Programming Languages',
            'kicker' => 'Beginner Friendly Python Training',
            'h1' => 'Python Programming Course in Jaipur',
            'lead' => 'Start coding with Python through practical examples, logic building, functions, files, OOP and small project-based exercises.',
            'image' => 'assets/images/courses/home14/3.jpg',
            'icon' => 'fa-code',
            'chips' => ['Python Basics', 'OOP', 'Files', 'Modules', 'Mini Projects'],
            'modules' => ['Python setup and syntax', 'Variables, operators and control flow', 'Loops and problem solving', 'Functions and modules', 'Lists, tuples, sets and dictionaries', 'File handling and exceptions', 'OOP concepts', 'Mini project and interview basics'],
            'projects' => ['Calculator and logic tasks', 'Student marks analyzer', 'File-based mini app', 'Python automation mini project'],
            'roles' => ['Python Trainee', 'Automation Learner', 'Backend Beginner', 'Data Analytics Beginner'],
        ],
        'python-full-stack' => [
            'slug' => 'python-full-stack-course-jaipur.php',
            'title' => 'Python Full Stack Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn Python Full Stack in Jaipur with frontend, Python backend, database, APIs, Django or Flask concepts and practical projects.',
            'category' => 'Full Stack Development',
            'kicker' => 'Python Backend and Web App Training',
            'h1' => 'Python Full Stack Course in Jaipur',
            'lead' => 'Build Python web applications by connecting responsive frontend screens, backend routes, databases and API workflows.',
            'image' => 'assets/images/courses/home14/3.jpg',
            'icon' => 'fa-code',
            'chips' => ['Python', 'Django', 'Flask', 'REST APIs', 'SQL'],
            'modules' => ['Python programming revision', 'Frontend foundations', 'Backend routing concepts', 'Django or Flask fundamentals', 'Database models and CRUD', 'Forms, validation and sessions', 'API integration', 'Project and deployment basics'],
            'projects' => ['Student portal', 'Lead management dashboard', 'Blog CMS workflow', 'Final Python full stack app'],
            'roles' => ['Python Developer', 'Backend Developer', 'Full Stack Developer', 'Django Trainee'],
        ],
        'data-science' => [
            'slug' => 'data-science-course-jaipur.php',
            'title' => 'Data Science Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn Data Science in Jaipur with Python, statistics, data cleaning, visualization, machine learning basics and practical projects.',
            'category' => 'Data Science and AI',
            'kicker' => 'Python, Statistics and ML Training',
            'h1' => 'Data Science Course in Jaipur',
            'lead' => 'Understand how data is cleaned, analyzed, visualized and used for machine learning models through practical Python workflows.',
            'image' => 'assets/images/courses/home14/4.jpg',
            'icon' => 'fa-line-chart',
            'chips' => ['Python', 'Statistics', 'Pandas', 'Visualization', 'Machine Learning'],
            'modules' => ['Python for data work', 'Statistics and probability basics', 'NumPy and Pandas', 'Data cleaning and EDA', 'Visualization with charts', 'Machine learning fundamentals', 'Model evaluation', 'Capstone data project'],
            'projects' => ['Sales analysis dashboard', 'Customer segmentation', 'Prediction model basics', 'Data science capstone project'],
            'roles' => ['Data Analyst', 'Data Science Trainee', 'ML Beginner', 'Business Analytics Learner'],
        ],
        'artificial-intelligence' => [
            'slug' => 'artificial-intelligence-course-jaipur.php',
            'title' => 'Artificial Intelligence Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn Artificial Intelligence in Jaipur with Python, ML foundations, neural network basics, generative AI concepts and practical use cases.',
            'category' => 'Data Science and AI',
            'kicker' => 'AI Concepts and Practical Workflows',
            'h1' => 'Artificial Intelligence Course in Jaipur',
            'lead' => 'Learn AI foundations through Python, machine learning concepts, model thinking, generative AI tools and applied project workflows.',
            'image' => 'assets/images/courses/home14/4.jpg',
            'icon' => 'fa-lightbulb-o',
            'chips' => ['AI Basics', 'Python', 'Machine Learning', 'Neural Networks', 'Gen AI'],
            'modules' => ['AI fundamentals', 'Python for AI', 'Data and model thinking', 'Machine learning basics', 'Neural network overview', 'NLP and computer vision overview', 'Generative AI use cases', 'AI project presentation'],
            'projects' => ['AI use case planner', 'Text classification demo', 'Prediction workflow', 'AI mini capstone'],
            'roles' => ['AI Trainee', 'ML Beginner', 'Automation Learner', 'Data Science Learner'],
        ],
        'cloud-computing' => [
            'slug' => 'cloud-computing-course-jaipur.php',
            'title' => 'Cloud Computing Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn Cloud Computing in Jaipur with AWS fundamentals, Linux basics, deployment concepts, networking, storage, security and DevOps workflow.',
            'category' => 'Cloud and DevOps',
            'kicker' => 'AWS, Deployment and DevOps Basics',
            'h1' => 'Cloud Computing Course in Jaipur',
            'lead' => 'Understand cloud platforms, servers, storage, networking, security basics and deployment workflows used in modern IT teams.',
            'image' => 'assets/images/courses/home14/5.jpg',
            'icon' => 'fa-cloud',
            'chips' => ['AWS', 'Linux', 'Networking', 'Deployment', 'DevOps'],
            'modules' => ['Cloud fundamentals', 'Linux and server basics', 'AWS compute and storage', 'Networking and DNS basics', 'Identity and security basics', 'Deployment workflow', 'Monitoring overview', 'Cloud project practice'],
            'projects' => ['Static website deployment', 'Server setup checklist', 'Cloud storage workflow', 'Mini DevOps deployment project'],
            'roles' => ['Cloud Trainee', 'AWS Beginner', 'DevOps Learner', 'System Support Trainee'],
        ],
        'cyber-security' => [
            'slug' => 'cyber-security-course-jaipur.php',
            'title' => 'Cyber Security Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn Cyber Security in Jaipur with networking basics, Linux, web security, ethical hacking workflow, SOC concepts and practical labs.',
            'category' => 'Cyber Security',
            'kicker' => 'Security, Networking and Practical Labs',
            'h1' => 'Cyber Security Course in Jaipur',
            'lead' => 'Build cyber security foundations through networking, Linux, web security, threat awareness, practical labs and career-oriented revision.',
            'image' => 'assets/images/courses/home14/6.jpg',
            'icon' => 'fa-shield',
            'chips' => ['Networking', 'Linux', 'Web Security', 'SOC Basics', 'Ethical Hacking'],
            'modules' => ['Security fundamentals', 'Networking basics', 'Linux essentials', 'Web application security', 'Vulnerability assessment', 'SOC and log basics', 'Reporting and documentation', 'Security lab project'],
            'projects' => ['Security checklist audit', 'Basic vulnerability report', 'Log review exercise', 'Cyber security mini lab'],
            'roles' => ['Security Analyst Trainee', 'SOC Beginner', 'Cyber Security Trainee', 'Network Security Learner'],
        ],
        'digital-marketing' => [
            'slug' => 'digital-marketing-course-jaipur.php',
            'title' => 'Digital Marketing Course in Jaipur | Jaipur Engineers',
            'meta' => 'Learn Digital Marketing in Jaipur with SEO, Google Ads, social media marketing, content planning, analytics and practical campaign workflows.',
            'category' => 'Digital Marketing',
            'kicker' => 'SEO, Ads and Campaign Training',
            'h1' => 'Digital Marketing Course in Jaipur',
            'lead' => 'Learn practical digital marketing through SEO, paid campaigns, content planning, social media, analytics and local business growth workflows.',
            'image' => 'assets/images/courses/style5/5.jpg',
            'icon' => 'fa-bullhorn',
            'chips' => ['SEO', 'Google Ads', 'Social Media', 'Analytics', 'Content'],
            'modules' => ['Digital marketing foundations', 'Website and landing page basics', 'SEO fundamentals', 'Google Ads workflow', 'Social media planning', 'Content and creatives', 'Analytics and reporting', 'Campaign project'],
            'projects' => ['SEO audit plan', 'Google Ads structure', 'Social media calendar', 'Local business campaign project'],
            'roles' => ['Digital Marketing Executive', 'SEO Trainee', 'Ads Trainee', 'Social Media Executive'],
        ],
    ];
    foreach ($pages as &$page) {
        $page['image'] = je_course_card_image($page['slug'], $page['image']);
    }
    unset($page);
    return $pages;
}

function je_get_course_page(string $key): ?array
{
    $pages = je_course_pages();
    return $pages[$key] ?? null;
}
?>
