<?php
/** Canonical uploaded course cards; shared by the catalog and course templates. */
function je_course_cards(): array
{
    return [
        'angular-course-jaipur.php' => [
            'slug' => 'angular-course-jaipur.php',
            'h1' => 'Angular Course in Jaipur',
            'category' => 'Frontend Development',
            'lead' => 'Learn Angular through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/angular-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-code',
            'chips' => ['Angular','TypeScript','Components','Services','RxJS'],
        ],
        'api-testing-course-jaipur.php' => [
            'slug' => 'api-testing-course-jaipur.php',
            'h1' => 'API Testing Course in Jaipur',
            'category' => 'Software Testing',
            'lead' => 'Learn API Testing through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/api-testing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-exchange',
            'chips' => ['REST APIs','Postman','JSON','Assertions','Automation'],
        ],
        'artificial-intelligence-course-jaipur.php' => [
            'slug' => 'artificial-intelligence-course-jaipur.php',
            'h1' => 'Artificial Intelligence Course in Jaipur',
            'category' => 'Data Science and AI',
            'lead' => 'Learn AI foundations through Python, machine learning concepts, model thinking, generative AI tools and applied project workflows.',
            'image' => 'assets/images/artificial-intelligence-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-lightbulb-o',
            'chips' => ['AI Basics', 'Python', 'Machine Learning', 'Neural Networks', 'Gen AI'],
        ],
        'automation-testing-course-jaipur.php' => [
            'slug' => 'automation-testing-course-jaipur.php',
            'h1' => 'Automation Testing Course in Jaipur',
            'category' => 'Software Testing',
            'lead' => 'Learn Automation Testing through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/automation-testing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cogs',
            'chips' => ['Automation','Selenium','Frameworks','Test Scripts','CI Basics'],
        ],
        'azure-course-jaipur.php' => [
            'slug' => 'azure-course-jaipur.php',
            'h1' => 'Microsoft Azure Course in Jaipur',
            'category' => 'Cloud Computing',
            'lead' => 'Learn Microsoft Azure through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/azure-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cloud',
            'chips' => ['Azure','Virtual Machines','Storage','Networking','Identity'],
        ],
        'big-data-java-course-jaipur.php' => [
            'slug' => 'big-data-java-course-jaipur.php',
            'h1' => 'Big Data with Java Course in Jaipur',
            'category' => 'Java and Big Data',
            'lead' => 'Learn Big Data with Java through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/big-data-java-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-database',
            'chips' => ['Java','Big Data','Hadoop','Data Processing','Distributed Systems'],
        ],
        'ceh-course-jaipur.php' => [
            'slug' => 'ceh-course-jaipur.php',
            'h1' => 'CEH Training Course in Jaipur',
            'category' => 'Cyber Security',
            'lead' => 'Learn CEH Training through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/ceh-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-shield',
            'chips' => ['Ethical Hacking','Network Security','Web Security','Vulnerability Assessment','Labs'],
        ],
        'cloud-computing-course-jaipur.php' => [
            'slug' => 'cloud-computing-course-jaipur.php',
            'h1' => 'Cloud Computing Course in Jaipur',
            'category' => 'Cloud and DevOps',
            'lead' => 'Understand cloud platforms, servers, storage, networking, security basics and deployment workflows used in modern IT teams.',
            'image' => 'assets/images/cloud-computing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cloud',
            'chips' => ['AWS', 'Linux', 'Networking', 'Deployment', 'DevOps'],
        ],
        'content-marketing-course-jaipur.php' => [
            'slug' => 'content-marketing-course-jaipur.php',
            'h1' => 'Content Marketing Course in Jaipur',
            'category' => 'Digital Marketing',
            'lead' => 'Learn Content Marketing through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/content-marketing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-pencil',
            'chips' => ['Content Strategy','SEO Content','Blogs','Social Content','Analytics'],
        ],
        'core-java-course-jaipur.php' => [
            'slug' => 'core-java-course-jaipur.php',
            'h1' => 'Core Java Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Core Java through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/core-java-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-coffee',
            'chips' => ['J2SE','OOP','Collections','Exceptions','JDBC'],
        ],
        'cyber-security-course-jaipur.php' => [
            'slug' => 'cyber-security-course-jaipur.php',
            'h1' => 'Cyber Security Course in Jaipur',
            'category' => 'Cyber Security',
            'lead' => 'Build cyber security foundations through networking, Linux, web security, threat awareness, practical labs and career-oriented revision.',
            'image' => 'assets/images/cyber-security-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-shield',
            'chips' => ['Networking', 'Linux', 'Web Security', 'SOC Basics', 'Ethical Hacking'],
        ],
        'data-analytics-course-jaipur.php' => [
            'slug' => 'data-analytics-course-jaipur.php',
            'h1' => 'Data Analytics Course in Jaipur',
            'category' => 'Data Analytics',
            'lead' => 'Learn Data Analytics through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/data-analytics-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-line-chart',
            'chips' => ['Excel','SQL','Power BI','Python','Data Visualization'],
        ],
        'data-science-course-jaipur.php' => [
            'slug' => 'data-science-course-jaipur.php',
            'h1' => 'Data Science Course in Jaipur',
            'category' => 'Data Science and AI',
            'lead' => 'Understand how data is cleaned, analyzed, visualized and used for machine learning models through practical Python workflows.',
            'image' => 'assets/images/data-science-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-line-chart',
            'chips' => ['Python', 'Statistics', 'Pandas', 'Visualization', 'Machine Learning'],
        ],
        'digital-marketing-course-jaipur.php' => [
            'slug' => 'digital-marketing-course-jaipur.php',
            'h1' => 'Digital Marketing Course in Jaipur',
            'category' => 'Digital Marketing',
            'lead' => 'Learn practical digital marketing through SEO, paid campaigns, content planning, social media, analytics and local business growth workflows.',
            'image' => 'assets/images/digital-marketing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-bullhorn',
            'chips' => ['SEO', 'Google Ads', 'Social Media', 'Analytics', 'Content'],
        ],
        'docker-course-jaipur.php' => [
            'slug' => 'docker-course-jaipur.php',
            'h1' => 'Docker Course in Jaipur',
            'category' => 'Cloud and DevOps',
            'lead' => 'Learn Docker through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/docker-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cube',
            'chips' => ['Docker','Images','Containers','Dockerfile','Compose'],
        ],
        'dotnet-full-stack-course-jaipur.php' => [
            'slug' => 'dotnet-full-stack-course-jaipur.php',
            'h1' => 'ASP.NET Full Stack Course in Jaipur',
            'category' => 'Full Stack Development',
            'lead' => 'Learn ASP.NET Full Stack through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/dotnet-full-stack-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-windows',
            'chips' => ['C#','ASP.NET Core','Web API','SQL','Frontend'],
        ],
        'email-marketing-course-jaipur.php' => [
            'slug' => 'email-marketing-course-jaipur.php',
            'h1' => 'Email Marketing Course in Jaipur',
            'category' => 'Digital Marketing',
            'lead' => 'Learn Email Marketing through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/email-marketing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-envelope',
            'chips' => ['Email Campaigns','Lists','Automation','Copywriting','Analytics'],
        ],
        'ethical-hacking-course-jaipur.php' => [
            'slug' => 'ethical-hacking-course-jaipur.php',
            'h1' => 'Ethical Hacking Course in Jaipur',
            'category' => 'Cyber Security',
            'lead' => 'Learn Ethical Hacking through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/ethical-hacking-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-shield',
            'chips' => ['Networking','Linux','Reconnaissance','Web Security','Security Labs'],
        ],
        'generative-ai-course-jaipur.php' => [
            'slug' => 'generative-ai-course-jaipur.php',
            'h1' => 'Generative AI Course in Jaipur',
            'category' => 'Data Science and AI',
            'lead' => 'Learn Generative AI through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/generative-ai-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-lightbulb-o',
            'chips' => ['Generative AI','Prompt Engineering','LLMs','AI Tools','Applied Projects'],
        ],
        'google-cloud-course-jaipur.php' => [
            'slug' => 'google-cloud-course-jaipur.php',
            'h1' => 'Google Cloud Course in Jaipur',
            'category' => 'Cloud Computing',
            'lead' => 'Learn Google Cloud through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/google-cloud-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cloud',
            'chips' => ['Google Cloud','Compute','Storage','Networking','IAM'],
        ],
        'hadoop-course-jaipur.php' => [
            'slug' => 'hadoop-course-jaipur.php',
            'h1' => 'Hadoop Course in Jaipur',
            'category' => 'Big Data',
            'lead' => 'Learn Hadoop through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/hadoop-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-database',
            'chips' => ['Hadoop','HDFS','MapReduce','YARN','Big Data'],
        ],
        'helidon-course-jaipur.php' => [
            'slug' => 'helidon-course-jaipur.php',
            'h1' => 'Helidon Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Helidon through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/helidon-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cloud',
            'chips' => ['Helidon','Microservices','REST','Cloud Native','Java'],
        ],
        'hibernate-course-jaipur.php' => [
            'slug' => 'hibernate-course-jaipur.php',
            'h1' => 'Hibernate Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Hibernate through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/hibernate-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-database',
            'chips' => ['Hibernate','ORM','Entities','Mappings','HQL'],
        ],
        'java-courses-jaipur.php' => [
            'slug' => 'java-courses-jaipur.php',
            'h1' => 'Java Courses in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Java Courses through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/java-courses-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-coffee',
            'chips' => ['Core Java','Advanced Java','Spring Boot','Hibernate','REST APIs'],
        ],
        'java-design-patterns-course-jaipur.php' => [
            'slug' => 'java-design-patterns-course-jaipur.php',
            'h1' => 'Java Design Patterns Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Java Design Patterns through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/java-design-patterns-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cogs',
            'chips' => ['SOLID','Creational','Structural','Behavioral','Architecture'],
        ],
        'java-full-stack-course-jaipur.php' => [
            'slug' => 'java-full-stack-course-jaipur.php',
            'h1' => 'Java Full Stack Course in Jaipur',
            'category' => 'Full Stack Development',
            'lead' => 'Build Java web applications with Core Java, Spring Boot, REST APIs, Hibernate, MySQL and frontend integration.',
            'image' => 'assets/images/java-full-stack-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-leaf',
            'chips' => ['Core Java', 'Spring Boot', 'REST APIs', 'Hibernate', 'MySQL'],
        ],
        'java-interview-preparation-jaipur.php' => [
            'slug' => 'java-interview-preparation-jaipur.php',
            'h1' => 'Java Interview Preparation in Jaipur',
            'category' => 'Career Preparation',
            'lead' => 'Learn Java Interview Preparation through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/java-interview-preparation-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-briefcase',
            'chips' => ['Core Java','OOP','Collections','Spring Boot','Interview Practice'],
        ],
        'java-microservices-course-jaipur.php' => [
            'slug' => 'java-microservices-course-jaipur.php',
            'h1' => 'Java Microservices Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Java Microservices through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/java-microservices-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-server',
            'chips' => ['Microservices','Spring Boot','REST APIs','Service Design','Deployment'],
        ],
        'java-multithreading-course-jaipur.php' => [
            'slug' => 'java-multithreading-course-jaipur.php',
            'h1' => 'Java Multithreading Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Java Multithreading through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/java-multithreading-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cogs',
            'chips' => ['Threads','Concurrency','Synchronization','Executors','Locks'],
        ],
        'java-rest-api-course-jaipur.php' => [
            'slug' => 'java-rest-api-course-jaipur.php',
            'h1' => 'Java REST API Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Java REST API through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/java-rest-api-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-exchange',
            'chips' => ['REST APIs','Spring Boot','JSON','Validation','Postman'],
        ],
        'jpa-course-jaipur.php' => [
            'slug' => 'jpa-course-jaipur.php',
            'h1' => 'JPA Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn JPA through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/jpa-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-database',
            'chips' => ['JPA','Entities','Repositories','Relationships','JPQL'],
        ],
        'kafka-java-course-jaipur.php' => [
            'slug' => 'kafka-java-course-jaipur.php',
            'h1' => 'Kafka with Java Course in Jaipur',
            'category' => 'Java and Big Data',
            'lead' => 'Learn Kafka with Java through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/kafka-java-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-exchange',
            'chips' => ['Apache Kafka','Java','Producers','Consumers','Streaming'],
        ],
        'kubernetes-course-jaipur.php' => [
            'slug' => 'kubernetes-course-jaipur.php',
            'h1' => 'Kubernetes Course in Jaipur',
            'category' => 'Cloud and DevOps',
            'lead' => 'Learn Kubernetes through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/kubernetes-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-cubes',
            'chips' => ['Kubernetes','Pods','Deployments','Services','Helm'],
        ],
        'machine-learning-course-jaipur.php' => [
            'slug' => 'machine-learning-course-jaipur.php',
            'h1' => 'Machine Learning Course in Jaipur',
            'category' => 'Data Science and AI',
            'lead' => 'Learn Machine Learning through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/machine-learning-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-line-chart',
            'chips' => ['Python','Supervised Learning','Unsupervised Learning','Model Evaluation','Projects'],
        ],
        'manual-testing-course-jaipur.php' => [
            'slug' => 'manual-testing-course-jaipur.php',
            'h1' => 'Manual Testing Course in Jaipur',
            'category' => 'Software Testing',
            'lead' => 'Learn Manual Testing through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/manual-testing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-check-square-o',
            'chips' => ['SDLC','STLC','Test Cases','Bug Reporting','Agile Testing'],
        ],
        'mean-stack-course-jaipur.php' => [
            'slug' => 'mean-stack-course-jaipur.php',
            'h1' => 'MEAN Stack Course in Jaipur',
            'category' => 'Full Stack Development',
            'lead' => 'Learn MEAN Stack through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/mean-stack-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-code',
            'chips' => ['MongoDB','Express.js','Angular','Node.js','REST APIs'],
        ],
        'mern-stack-course-jaipur.php' => [
            'slug' => 'mern-stack-course-jaipur.php',
            'h1' => 'MERN Stack Course in Jaipur',
            'category' => 'Full Stack Development',
            'lead' => 'Learn MERN Stack through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/mern-stack-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-code',
            'chips' => ['MongoDB','Express.js','React.js','Node.js','REST APIs'],
        ],
        'network-security-course-jaipur.php' => [
            'slug' => 'network-security-course-jaipur.php',
            'h1' => 'Network Security Course in Jaipur',
            'category' => 'Cyber Security',
            'lead' => 'Learn Network Security through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/network-security-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-shield',
            'chips' => ['Networking','Firewalls','VPN','Hardening','Monitoring'],
        ],
        'next-js-course-jaipur.php' => [
            'slug' => 'next-js-course-jaipur.php',
            'h1' => 'Next.js Course in Jaipur',
            'category' => 'Full Stack Development',
            'lead' => 'Learn Next.js through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/next-js-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-code',
            'chips' => ['Next.js','React','Routing','Server Rendering','APIs'],
        ],
        'node-js-course-jaipur.php' => [
            'slug' => 'node-js-course-jaipur.php',
            'h1' => 'Node.js Course in Jaipur',
            'category' => 'Backend Development',
            'lead' => 'Learn Node.js through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/node-js-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-server',
            'chips' => ['Node.js','Express.js','REST APIs','Database','Authentication'],
        ],
        'penetration-testing-course-jaipur.php' => [
            'slug' => 'penetration-testing-course-jaipur.php',
            'h1' => 'Penetration Testing Course in Jaipur',
            'category' => 'Cyber Security',
            'lead' => 'Learn Penetration Testing through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/penetration-testing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-shield',
            'chips' => ['Reconnaissance','Scanning','Web Testing','Reporting','Security Labs'],
        ],
        'python-full-stack-course-jaipur.php' => [
            'slug' => 'python-full-stack-course-jaipur.php',
            'h1' => 'Python Full Stack Course in Jaipur',
            'category' => 'Full Stack Development',
            'lead' => 'Build Python web applications by connecting responsive frontend screens, backend routes, databases and API workflows.',
            'image' => 'assets/images/python-full-stack-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-code',
            'chips' => ['Python', 'Django', 'Flask', 'REST APIs', 'SQL'],
        ],
        'seo-course-jaipur.php' => [
            'slug' => 'seo-course-jaipur.php',
            'h1' => 'SEO Course in Jaipur',
            'category' => 'Digital Marketing',
            'lead' => 'Learn SEO through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/seo-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-search',
            'chips' => ['On-Page SEO','Technical SEO','Keywords','Link Building','Search Console'],
        ],
        'soc-analyst-course-jaipur.php' => [
            'slug' => 'soc-analyst-course-jaipur.php',
            'h1' => 'SOC Analyst Course in Jaipur',
            'category' => 'Cyber Security',
            'lead' => 'Learn SOC Analyst through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/soc-analyst-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-shield',
            'chips' => ['SOC','SIEM','Log Analysis','Incident Response','Threat Monitoring'],
        ],
        'social-media-marketing-course-jaipur.php' => [
            'slug' => 'social-media-marketing-course-jaipur.php',
            'h1' => 'Social Media Marketing Course in Jaipur',
            'category' => 'Digital Marketing',
            'lead' => 'Learn Social Media Marketing through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/social-media-marketing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-share-alt',
            'chips' => ['Social Media','Content Planning','Meta Ads','Analytics','Campaigns'],
        ],
        'software-testing-course-jaipur.php' => [
            'slug' => 'software-testing-course-jaipur.php',
            'h1' => 'Software Testing Course in Jaipur',
            'category' => 'Software Testing',
            'lead' => 'Learn Software Testing through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/software-testing-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-check-square-o',
            'chips' => ['Manual Testing','Automation','API Testing','Selenium','Test Cases'],
        ],
        'spring-boot-course-jaipur.php' => [
            'slug' => 'spring-boot-course-jaipur.php',
            'h1' => 'Spring Boot Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Spring Boot through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/spring-boot-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-leaf',
            'chips' => ['Spring Boot','REST APIs','JPA','Validation','Microservices'],
        ],
        'spring-framework-course-jaipur.php' => [
            'slug' => 'spring-framework-course-jaipur.php',
            'h1' => 'Spring Framework Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Spring Framework through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/spring-framework-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-leaf',
            'chips' => ['Spring Core','Dependency Injection','Beans','AOP','Spring MVC'],
        ],
        'spring-mvc-course-jaipur.php' => [
            'slug' => 'spring-mvc-course-jaipur.php',
            'h1' => 'Spring MVC Course in Jaipur',
            'category' => 'Java Development',
            'lead' => 'Learn Spring MVC through practical, trainer-guided learning, assignments and project-oriented training at Jaipur Engineers.',
            'image' => 'assets/images/spring-mvc-course-jaipur-jaipur-engineers.webp',
            'icon' => 'fa-leaf',
            'chips' => ['Spring MVC','Controllers','Views','Validation','Forms'],
        ],
    ];
}

function je_course_card_image(string $slug, string $fallback): string
{
    // Existing alternate course URLs share the corresponding canonical artwork.
    $aliases = [
        'angular-development-course-jaipur.php' => 'angular-course-jaipur.php',
        'node-js-development-course-jaipur.php' => 'node-js-course-jaipur.php',
    ];
    $cards = je_course_cards();
    return $cards[$aliases[$slug] ?? $slug]['image'] ?? $fallback;
}
