<?php
$articles = [
    ['title' => 'AI Leaders Call for a Safer Pace as Frontier AI Risks Grow','slug' => 'ai-leaders-call-for-safer-pace-frontier-ai-risks','date' => 'September 14, 2026','category' => 'Artificial Intelligence','excerpt' => 'Anthropic, OpenAI and other AI leaders are calling for stronger safeguards and a more measured pace of frontier AI development.'],
    ['title' => 'AI-Linked Stocks Slide After Calls to Slow Frontier AI Development','slug' => 'ai-linked-stocks-slide-after-frontier-ai-slowdown-calls','date' => 'September 14, 2026','category' => 'Technology Business','excerpt' => 'Fresh warnings from leading AI executives are putting safety, investment expectations and AI infrastructure spending back in focus.'],
    ['title' => 'India’s Telecom Sector Looks to AI for More Autonomous Networks','slug' => 'india-telecom-sector-ai-autonomous-networks','date' => 'September 14, 2026','category' => 'AI in India','excerpt' => 'India’s telecom sector is exploring greater AI-driven network autonomy while regulators emphasize accountability and human oversight.'],
    ['title' => 'Gridlock Hackathon 2.0 Shows How AI Hackathons Can Solve Real-World Problems','slug' => 'hackathon-news-2026','date' => 'September 14, 2026','category' => 'Hackathon News','excerpt' => '33,600 participants created more than 1,100 AI and machine-learning prototypes for Bengaluru traffic and urban mobility challenges.'],
    ['title' => 'Upcoming Hackathon Events in Jaipur and India: September 2026','slug' => 'jaipur-hackathon-events-september-2026','date' => 'September 14, 2026','category' => 'Hackathon Events','excerpt' => 'A roundup of upcoming September hackathons covering AI, Web3, hardware, software and student innovation.'],
];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Technology News | Latest AI, Tech & Hackathon News | Jaipur Engineers</title><meta name="description" content="Latest technology news, AI updates, cybersecurity, software trends, hackathon news and upcoming technology events from India and around the world."><meta name="keywords" content="technology news, AI news, India technology news, hackathon news, hackathon events Jaipur, software news, cybersecurity news"><link rel="canonical" href="https://www.jaipurengineers.com/news/"></head><body><main><header><h1>Latest Technology & Hackathon News</h1><p>Technology, artificial intelligence, software, hackathons and digital industry updates.</p></header><section aria-label="Technology news articles"><?php foreach ($articles as $article): ?><article><p><strong><?= htmlspecialchars($article['category']) ?></strong> · <?= htmlspecialchars($article['date']) ?></p><h2><a href="<?= htmlspecialchars($article['slug']) ?>.php"><?= htmlspecialchars($article['title']) ?></a></h2><p><?= htmlspecialchars($article['excerpt']) ?></p><a href="<?= htmlspecialchars($article['slug']) ?>.php">Read full story</a></article><?php endforeach; ?></section></main></body></html>
