CREATE TABLE IF NOT EXISTS je_leads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    email VARCHAR(180) NULL,
    course VARCHAR(180) NULL,
    qualification VARCHAR(180) NULL,
    college VARCHAR(220) NULL,
    study_year VARCHAR(80) NULL,
    city VARCHAR(120) NULL,
    preferred_branch VARCHAR(180) NULL,
    learning_mode VARCHAR(80) NULL,
    batch_preference VARCHAR(180) NULL,
    source VARCHAR(180) NULL,
    message TEXT NULL,
    conversation_json LONGTEXT NULL,
    page_url VARCHAR(500) NULL,
    referrer VARCHAR(500) NULL,
    utm_source VARCHAR(180) NULL,
    utm_medium VARCHAR(180) NULL,
    utm_campaign VARCHAR(180) NULL,
    utm_term VARCHAR(180) NULL,
    utm_content VARCHAR(180) NULL,
    user_agent VARCHAR(500) NULL,
    device VARCHAR(80) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'New',
    assigned_to VARCHAR(180) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_created_at (created_at),
    KEY idx_course (course),
    KEY idx_phone (phone),
    KEY idx_source (source),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
