<?php
/**
 * Non-secret email copy for Jaipur Engineers lead follow-ups.
 * Placeholders: {{name}}, {{course}}, {{course_url}}, {{message}}, {{site_url}}, {{contact_url}}
 */
return [
    'student_subject' => 'Thanks for contacting Jaipur Engineers — {{course}}',
    'student_html' => '<!doctype html><html><body style="margin:0;background:#f5f7fb;font-family:Arial,Helvetica,sans-serif;color:#1d2a3d"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f5f7fb;padding:24px 12px"><tr><td align="center"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e8edf3"><tr><td style="background:#f15a24;padding:20px 24px;color:#ffffff"><div style="font-size:22px;font-weight:700">Jaipur Engineers</div><div style="font-size:13px;margin-top:4px">Practical IT Training & Career-Focused Learning</div></td></tr><tr><td style="padding:28px 24px"><p style="margin:0 0 14px;font-size:16px">Hi {{name}},</p><p style="margin:0 0 16px;line-height:1.6">Thanks for your enquiry about <strong>{{course}}</strong>. We have received your details and our counselling team can help you with the current syllabus, batch options, learning mode and next steps.</p><div style="background:#fff7f2;border:1px solid #ffd9c7;border-radius:12px;padding:14px 16px;margin:18px 0"><div style="font-size:12px;font-weight:700;color:#9b3c17;text-transform:uppercase;letter-spacing:.06em">Your message</div><div style="margin-top:7px;line-height:1.55">{{message}}</div></div><p style="margin:0 0 10px;line-height:1.6"><strong>Why students explore Jaipur Engineers:</strong></p><ul style="padding-left:20px;margin:0 0 20px;line-height:1.7"><li>Practical, project-oriented technology training</li><li>Internship and live-project options for supported programs</li><li>Placement assistance and interview preparation support</li><li>Online / offline learning options depending on the current batch</li></ul><p style="margin:0 0 20px"><a href="{{course_url}}" style="display:inline-block;background:#17253a;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:9px;font-weight:700">View Course / Enquiry Page</a></p><p style="margin:0;line-height:1.6">You can also explore more programs at <a href="{{site_url}}" style="color:#d94d1b">Jaipur Engineers</a> or contact the counselling team from our <a href="{{contact_url}}" style="color:#d94d1b">contact page</a>.</p></td></tr><tr><td style="padding:16px 24px;background:#f8fafc;border-top:1px solid #e8edf3;font-size:11px;line-height:1.5;color:#667085">This email was sent because an enquiry was submitted using your email address on Jaipur Engineers. Current fees, batch timing and program availability are confirmed by the counselling team.</td></tr></table></td></tr></table></body></html>',
];
