<?php
session_start();
header('X-Robots-Tag: noindex, nofollow', true);
header('X-Content-Type-Options: nosniff');

$root = dirname(__DIR__);
require_once $root . '/includes/je-ai-system.php';

$configDir = $root . '/config';
$storageDir = $root . '/storage';
$lockFile = $configDir . '/install.lock';
$databaseFile = $configDir . '/database.php';
$mailFile = $configDir . '/mail.php';

if (empty($_SESSION['je_install_csrf'])) {
    $_SESSION['je_install_csrf'] = bin2hex(random_bytes(24));
}

$requirements = [
    'PHP 7.4+' => version_compare(PHP_VERSION, '7.4.0', '>='),
    'PDO extension' => class_exists('PDO'),
    'PDO MySQL driver' => class_exists('PDO') && in_array('mysql', PDO::getAvailableDrivers(), true),
    'JSON support' => function_exists('json_encode'),
    'OpenSSL / TLS support' => extension_loaded('openssl'),
    'Config directory writable' => is_writable($configDir),
    'Storage directory writable' => is_writable($storageDir),
];

$allRequirements = !in_array(false, $requirements, true);
$locked = is_file($lockFile);
$errors = [];
$success = '';
$mailTestMessage = '';

function je_install_h($value)
{
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

function je_install_value($name, $default = '')
{
    return isset($_POST[$name]) ? (string)$_POST[$name] : $default;
}

function je_install_write_config($path, array $data)
{
    $php = "<?php\n// Generated by Jaipur Engineers /install. Do not commit this file.\nreturn " . var_export($data, true) . ";\n";
    $temp = $path . '.tmp-' . bin2hex(random_bytes(4));
    if (@file_put_contents($temp, $php, LOCK_EX) === false) {
        throw new RuntimeException('Could not write configuration file: ' . basename($path));
    }
    @chmod($temp, 0640);
    if (!@rename($temp, $path)) {
        @unlink($temp);
        throw new RuntimeException('Could not activate configuration file: ' . basename($path));
    }
}

$existingDb = is_file($databaseFile) ? je_ai_runtime_config('database') : [];
$existingMail = is_file($mailFile) ? je_ai_runtime_config('mail') : [];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$locked) {
    $csrf = isset($_POST['csrf']) ? (string)$_POST['csrf'] : '';
    if ($csrf === '' || !hash_equals($_SESSION['je_install_csrf'], $csrf)) {
        $errors[] = 'Security token mismatch. Refresh the page and try again.';
    } elseif (!$allRequirements) {
        $errors[] = 'Please fix the failed server requirements before installation.';
    } else {
        $db = [
            'host' => trim(je_install_value('db_host', 'localhost')),
            'port' => (int)je_install_value('db_port', '3306'),
            'database' => trim(je_install_value('db_name')),
            'username' => trim(je_install_value('db_user')),
            'password' => je_install_value('db_pass'),
            'charset' => 'utf8mb4',
        ];

        if ($db['host'] === '' || $db['database'] === '' || $db['username'] === '') {
            $errors[] = 'Database host, database name and database username are required.';
        }
        if ($db['port'] < 1 || $db['port'] > 65535) {
            $errors[] = 'Database port is invalid.';
        }

        $mailEnabled = isset($_POST['mail_enabled']) && $_POST['mail_enabled'] === '1';
        $encryptionValue = je_install_value('smtp_encryption', 'ssl');
        $mail = [
            'enabled' => $mailEnabled,
            'driver' => je_install_value('mail_driver', 'smtp') === 'mail' ? 'mail' : 'smtp',
            'host' => trim(je_install_value('smtp_host', 'smtp.hostinger.com')),
            'port' => (int)je_install_value('smtp_port', '465'),
            'encryption' => in_array($encryptionValue, ['tls', 'ssl', 'none'], true) ? $encryptionValue : 'ssl',
            'username' => trim(je_install_value('smtp_user', 'info@jaipurengineers.com')),
            'password' => je_install_value('smtp_pass'),
            'from_email' => trim(je_install_value('from_email', 'info@jaipurengineers.com')),
            'from_name' => trim(je_install_value('from_name', 'Jaipur Engineers')) ?: 'Jaipur Engineers',
            'notify_email' => trim(je_install_value('notify_email', 'mygrootacademy@gmail.com')),
        ];

        if ($mailEnabled) {
            if (!filter_var($mail['from_email'], FILTER_VALIDATE_EMAIL)) {
                $errors[] = 'A valid From email is required when mail notifications are enabled.';
            }
            if (!filter_var($mail['notify_email'], FILTER_VALIDATE_EMAIL)) {
                $errors[] = 'A valid lead notification email is required when mail notifications are enabled.';
            }
            if ($mail['driver'] === 'smtp' && ($mail['host'] === '' || $mail['port'] < 1 || $mail['port'] > 65535)) {
                $errors[] = 'SMTP host and a valid SMTP port are required.';
            }
        }

        if (!$errors) {
            try {
                $pdo = je_ai_db($db);
                je_ai_install_schema($pdo);
            } catch (Throwable $e) {
                $errors[] = 'Database check failed: ' . $e->getMessage();
            }
        }

        $sendTest = isset($_POST['send_test']) && $_POST['send_test'] === '1';
        if (!$errors && $mailEnabled && $sendTest) {
            $mailError = '';
            $testBody = "Jaipur Engineers website mail test\n\nIf you received this message, the /install mail settings are working.\nTime: " . date('c');
            $ok = je_ai_send_mail($mail, $mail['notify_email'], 'Jaipur Engineers website mail test', $testBody, $mailError);
            if (!$ok) {
                $errors[] = 'Mail test failed: ' . $mailError;
            } else {
                $mailTestMessage = 'Test email sent successfully to ' . $mail['notify_email'] . '.';
            }
        }

        if (!$errors) {
            try {
                je_install_write_config($databaseFile, $db);
                je_install_write_config($mailFile, $mail);
                $lockData = "Installed: " . gmdate('c') . "\nSchema: je_leads\nPHP: " . PHP_VERSION . "\n";
                if (@file_put_contents($lockFile, $lockData, LOCK_EX) === false) {
                    throw new RuntimeException('Could not create config/install.lock.');
                }
                @chmod($lockFile, 0640);
                $locked = true;
                $success = 'Installation completed. Database connection passed, je_leads is ready, mail settings were saved, and /install is now locked.';
            } catch (Throwable $e) {
                $errors[] = $e->getMessage();
            }
        }
    }
}
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Jaipur Engineers Website Installer</title>
<style>
:root{--orange:#f15a24;--dark:#18263a;--muted:#667085;--line:#e6eaf0;--bg:#f6f8fb;--ok:#087a52;--bad:#b42318}*{box-sizing:border-box}body{margin:0;background:var(--bg);font-family:Arial,Helvetica,sans-serif;color:var(--dark)}.wrap{max-width:980px;margin:34px auto;padding:0 18px}.hero,.card{background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:0 10px 28px rgba(19,33,54,.06)}.hero{padding:24px;margin-bottom:18px;border-top:4px solid var(--orange)}h1{margin:0 0 8px;font-size:27px}.hero p{margin:0;color:var(--muted);line-height:1.55}.card{padding:22px;margin-bottom:18px}h2{margin:0 0 16px;font-size:19px}.requirements{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.req{border:1px solid var(--line);border-radius:10px;padding:9px 11px;font-size:13px}.req.ok{background:#effaf5;color:var(--ok)}.req.bad{background:#fff1f0;color:var(--bad)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.field{display:flex;flex-direction:column;gap:6px}.full{grid-column:1/-1}label{font-size:12px;font-weight:700}.hint{font-size:11px;color:var(--muted);line-height:1.4}input,select{width:100%;border:1px solid #d8dee8;border-radius:9px;padding:10px 11px;font-size:14px;background:#fff}input:focus,select:focus{outline:2px solid rgba(241,90,36,.15);border-color:#f69a70}.check{display:flex;align-items:flex-start;gap:8px;margin:4px 0 15px}.check input{width:auto;margin-top:2px}.btn{border:0;border-radius:10px;background:var(--orange);color:#fff;font-weight:700;padding:12px 18px;cursor:pointer}.btn:disabled{opacity:.5}.alert{border-radius:11px;padding:12px 14px;margin-bottom:16px;font-size:13px;line-height:1.5}.alert.bad{background:#fff1f0;color:var(--bad);border:1px solid #ffd3cf}.alert.ok{background:#effaf5;color:var(--ok);border:1px solid #c7eedc}.locked{font-size:14px;line-height:1.6}.code{font-family:Consolas,monospace;background:#f2f4f7;border-radius:6px;padding:2px 6px}@media(max-width:700px){.grid,.requirements{grid-template-columns:1fr}.full{grid-column:auto}.wrap{margin:16px auto}.hero,.card{border-radius:13px;padding:17px}}
</style>
</head>
<body>
<div class="wrap">
    <div class="hero">
        <h1>Jaipur Engineers Website Installer</h1>
        <p>One-time setup for MySQL lead storage, admin lead alerts and student confirmation emails. Passwords stay only in hosting-side PHP config files ignored by Git.</p>
    </div>

    <?php if ($errors): ?><div class="alert bad"><strong>Setup not completed.</strong><br><?php echo implode('<br>', array_map('je_install_h', $errors)); ?></div><?php endif; ?>
    <?php if ($success): ?><div class="alert ok"><?php echo je_install_h($success); ?><?php if ($mailTestMessage): ?><br><?php echo je_install_h($mailTestMessage); ?><?php endif; ?></div><?php endif; ?>

    <div class="card">
        <h2>Server checks</h2>
        <div class="requirements">
            <?php foreach ($requirements as $label => $passed): ?>
                <div class="req <?php echo $passed ? 'ok' : 'bad'; ?>"><?php echo $passed ? '&#10003;' : '&#10007;'; ?> <?php echo je_install_h($label); ?></div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php if ($locked): ?>
        <div class="card locked">
            <h2>Installer locked</h2>
            <p>The setup lock exists at <span class="code">config/install.lock</span>. This prevents public changes to database or mail credentials.</p>
            <p>To reconfigure, delete <span class="code">config/install.lock</span> in Hostinger File Manager, reopen this page, update the values, then complete setup again.</p>
            <p><a href="/">Return to Jaipur Engineers website</a></p>
        </div>
    <?php else: ?>
    <form method="post" autocomplete="off">
        <input type="hidden" name="csrf" value="<?php echo je_install_h($_SESSION['je_install_csrf']); ?>">

        <div class="card">
            <h2>1. MySQL database</h2>
            <div class="grid">
                <div class="field"><label>DB Host *</label><input name="db_host" required value="<?php echo je_install_h(je_install_value('db_host', isset($existingDb['host']) ? $existingDb['host'] : 'localhost')); ?>"></div>
                <div class="field"><label>DB Port *</label><input name="db_port" inputmode="numeric" required value="<?php echo je_install_h(je_install_value('db_port', isset($existingDb['port']) ? $existingDb['port'] : '3306')); ?>"></div>
                <div class="field"><label>Database Name *</label><input name="db_name" required value="<?php echo je_install_h(je_install_value('db_name', isset($existingDb['database']) ? $existingDb['database'] : '')); ?>"></div>
                <div class="field"><label>Database User *</label><input name="db_user" required value="<?php echo je_install_h(je_install_value('db_user', isset($existingDb['username']) ? $existingDb['username'] : '')); ?>"></div>
                <div class="field full"><label>Database Password *</label><input type="password" name="db_pass" value="" placeholder="Enter hosting database password"><span class="hint">The password is written only to the ignored hosting config file.</span></div>
            </div>
        </div>

        <div class="card">
            <h2>2. Lead email notifications</h2>
            <label class="check"><input type="checkbox" name="mail_enabled" value="1" <?php echo (isset($_POST['mail_enabled']) || (!$_POST && (!empty($existingMail['enabled']) || empty($existingMail)))) ? 'checked' : ''; ?>><span><strong>Enable admin alerts and student confirmation emails</strong><br><span class="hint">Leads still save even if email delivery fails.</span></span></label>
            <div class="grid">
                <div class="field"><label>Mail Driver</label><select name="mail_driver"><option value="smtp" <?php echo je_install_value('mail_driver', isset($existingMail['driver']) ? $existingMail['driver'] : 'smtp') === 'smtp' ? 'selected' : ''; ?>>SMTP</option><option value="mail" <?php echo je_install_value('mail_driver') === 'mail' ? 'selected' : ''; ?>>PHP mail()</option></select></div>
                <div class="field"><label>Encryption</label><select name="smtp_encryption"><option value="ssl" <?php echo je_install_value('smtp_encryption', isset($existingMail['encryption']) ? $existingMail['encryption'] : 'ssl') === 'ssl' ? 'selected' : ''; ?>>SSL</option><option value="tls" <?php echo je_install_value('smtp_encryption') === 'tls' ? 'selected' : ''; ?>>TLS / STARTTLS</option><option value="none" <?php echo je_install_value('smtp_encryption') === 'none' ? 'selected' : ''; ?>>None</option></select></div>
                <div class="field"><label>SMTP Host</label><input name="smtp_host" value="<?php echo je_install_h(je_install_value('smtp_host', isset($existingMail['host']) ? $existingMail['host'] : 'smtp.hostinger.com')); ?>"></div>
                <div class="field"><label>SMTP Port</label><input name="smtp_port" inputmode="numeric" value="<?php echo je_install_h(je_install_value('smtp_port', isset($existingMail['port']) ? $existingMail['port'] : '465')); ?>"></div>
                <div class="field"><label>SMTP Username</label><input name="smtp_user" autocomplete="off" value="<?php echo je_install_h(je_install_value('smtp_user', isset($existingMail['username']) ? $existingMail['username'] : 'info@jaipurengineers.com')); ?>"></div>
                <div class="field"><label>SMTP Password</label><input type="password" name="smtp_pass" autocomplete="new-password" value="" placeholder="Mailbox password"></div>
                <div class="field"><label>From Email</label><input type="email" name="from_email" value="<?php echo je_install_h(je_install_value('from_email', isset($existingMail['from_email']) ? $existingMail['from_email'] : 'info@jaipurengineers.com')); ?>"></div>
                <div class="field"><label>From Name</label><input name="from_name" value="<?php echo je_install_h(je_install_value('from_name', isset($existingMail['from_name']) ? $existingMail['from_name'] : 'Jaipur Engineers')); ?>"></div>
                <div class="field full"><label>Send New Lead Alerts To</label><input type="email" name="notify_email" value="<?php echo je_install_h(je_install_value('notify_email', isset($existingMail['notify_email']) ? $existingMail['notify_email'] : 'mygrootacademy@gmail.com')); ?>"></div>
            </div>
            <label class="check" style="margin-top:15px"><input type="checkbox" name="send_test" value="1" checked><span><strong>Send a test email before locking setup</strong><br><span class="hint">If SMTP authentication fails, setup stays unlocked so you can correct the values.</span></span></label>
        </div>

        <div class="card">
            <h2>3. Create tables & finish</h2>
            <p class="hint">This tests MySQL, creates or upgrades <strong>je_leads</strong>, tests mail, writes protected runtime configs and creates the installer lock.</p>
            <button class="btn" type="submit" <?php echo !$allRequirements ? 'disabled' : ''; ?>>Test, Create Tables & Finish Setup</button>
        </div>
    </form>
    <?php endif; ?>
</div>
</body>
</html>
