<?php
/**
 * Jaipur Engineers AI assistant backend helpers.
 * No external AI API is required. Runtime DB/mail credentials are generated by /install.
 */

function je_ai_root()
{
    return dirname(__DIR__);
}

function je_ai_runtime_config($name)
{
    $allowed = ['database', 'mail'];
    if (!in_array($name, $allowed, true)) {
        return [];
    }

    $file = je_ai_root() . '/config/' . $name . '.php';
    if (!is_file($file)) {
        return [];
    }

    $value = require $file;
    return is_array($value) ? $value : [];
}

function je_ai_db(array $settings = null)
{
    if (!class_exists('PDO')) {
        throw new RuntimeException('PDO is not available on this server.');
    }

    $settings = $settings ?: je_ai_runtime_config('database');
    foreach (['host', 'database', 'username'] as $required) {
        if (empty($settings[$required])) {
            throw new RuntimeException('Database configuration is incomplete.');
        }
    }

    $host = (string)$settings['host'];
    $port = isset($settings['port']) ? (int)$settings['port'] : 3306;
    $charset = !empty($settings['charset']) ? (string)$settings['charset'] : 'utf8mb4';
    $database = (string)$settings['database'];
    $username = (string)$settings['username'];
    $password = isset($settings['password']) ? (string)$settings['password'] : '';

    $dsn = 'mysql:host=' . $host . ';port=' . $port . ';dbname=' . $database . ';charset=' . $charset;
    return new PDO($dsn, $username, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
}

function je_ai_install_schema(PDO $pdo)
{
    $sql = "CREATE TABLE IF NOT EXISTS `je_leads` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `session_id` VARCHAR(80) DEFAULT NULL,
        `name` VARCHAR(120) NOT NULL,
        `mobile` VARCHAR(30) NOT NULL,
        `email` VARCHAR(190) DEFAULT NULL,
        `interested_course` VARCHAR(190) DEFAULT NULL,
        `qualification` VARCHAR(190) DEFAULT NULL,
        `college` VARCHAR(190) DEFAULT NULL,
        `current_year` VARCHAR(80) DEFAULT NULL,
        `city` VARCHAR(120) DEFAULT NULL,
        `preferred_branch` VARCHAR(160) DEFAULT NULL,
        `learning_mode` VARCHAR(40) DEFAULT NULL,
        `preferred_batch` VARCHAR(120) DEFAULT NULL,
        `message` TEXT DEFAULT NULL,
        `source` VARCHAR(60) NOT NULL DEFAULT 'AI_CHAT',
        `page_url` TEXT DEFAULT NULL,
        `referrer` TEXT DEFAULT NULL,
        `utm_source` VARCHAR(190) DEFAULT NULL,
        `utm_medium` VARCHAR(190) DEFAULT NULL,
        `utm_campaign` VARCHAR(190) DEFAULT NULL,
        `utm_term` VARCHAR(190) DEFAULT NULL,
        `utm_content` VARCHAR(190) DEFAULT NULL,
        `device` VARCHAR(255) DEFAULT NULL,
        `conversation_json` LONGTEXT DEFAULT NULL,
        `status` VARCHAR(40) NOT NULL DEFAULT 'new',
        `assigned_to` VARCHAR(120) DEFAULT NULL,
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`),
        KEY `idx_je_leads_session` (`session_id`),
        KEY `idx_je_leads_mobile` (`mobile`),
        KEY `idx_je_leads_email` (`email`),
        KEY `idx_je_leads_status` (`status`),
        KEY `idx_je_leads_created` (`created_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";

    $pdo->exec($sql);

    // Additive upgrades keep existing compatible je_leads tables usable.
    $columns = [
        'session_id' => "VARCHAR(80) DEFAULT NULL",
        'interested_course' => "VARCHAR(190) DEFAULT NULL",
        'qualification' => "VARCHAR(190) DEFAULT NULL",
        'college' => "VARCHAR(190) DEFAULT NULL",
        'current_year' => "VARCHAR(80) DEFAULT NULL",
        'city' => "VARCHAR(120) DEFAULT NULL",
        'preferred_branch' => "VARCHAR(160) DEFAULT NULL",
        'learning_mode' => "VARCHAR(40) DEFAULT NULL",
        'preferred_batch' => "VARCHAR(120) DEFAULT NULL",
        'message' => "TEXT DEFAULT NULL",
        'source' => "VARCHAR(60) NOT NULL DEFAULT 'AI_CHAT'",
        'page_url' => "TEXT DEFAULT NULL",
        'referrer' => "TEXT DEFAULT NULL",
        'utm_source' => "VARCHAR(190) DEFAULT NULL",
        'utm_medium' => "VARCHAR(190) DEFAULT NULL",
        'utm_campaign' => "VARCHAR(190) DEFAULT NULL",
        'utm_term' => "VARCHAR(190) DEFAULT NULL",
        'utm_content' => "VARCHAR(190) DEFAULT NULL",
        'device' => "VARCHAR(255) DEFAULT NULL",
        'conversation_json' => "LONGTEXT DEFAULT NULL",
        'status' => "VARCHAR(40) NOT NULL DEFAULT 'new'",
        'assigned_to' => "VARCHAR(120) DEFAULT NULL",
        'updated_at' => "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
    ];

    $existing = [];
    $rows = $pdo->query('SHOW COLUMNS FROM `je_leads`')->fetchAll();
    foreach ($rows as $row) {
        if (!empty($row['Field'])) {
            $existing[(string)$row['Field']] = true;
        }
    }

    foreach ($columns as $column => $definition) {
        if (!isset($existing[$column])) {
            $pdo->exec('ALTER TABLE `je_leads` ADD COLUMN `' . $column . '` ' . $definition);
        }
    }
}

function je_ai_clean($value, $max = 255)
{
    if (is_array($value) || is_object($value)) {
        return '';
    }
    $value = trim((string)$value);
    $value = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u', '', $value);
    if (function_exists('mb_substr')) {
        return mb_substr($value, 0, $max, 'UTF-8');
    }
    return substr($value, 0, $max);
}

function je_ai_normalize_lead(array $input)
{
    $conversation = isset($input['conversation']) && is_array($input['conversation']) ? $input['conversation'] : [];
    if (count($conversation) > 60) {
        $conversation = array_slice($conversation, -60);
    }
    $safeConversation = [];
    foreach ($conversation as $message) {
        if (!is_array($message)) {
            continue;
        }
        $safeConversation[] = [
            'role' => isset($message['role']) && $message['role'] === 'assistant' ? 'assistant' : 'user',
            'text' => je_ai_clean(isset($message['text']) ? $message['text'] : '', 1200),
        ];
    }

    return [
        'session_id' => je_ai_clean(isset($input['session_id']) ? $input['session_id'] : '', 80),
        'name' => je_ai_clean(isset($input['name']) ? $input['name'] : '', 120),
        'mobile' => je_ai_clean(isset($input['mobile']) ? $input['mobile'] : '', 30),
        'email' => je_ai_clean(isset($input['email']) ? $input['email'] : '', 190),
        'interested_course' => je_ai_clean(isset($input['interested_course']) ? $input['interested_course'] : '', 190),
        'qualification' => je_ai_clean(isset($input['qualification']) ? $input['qualification'] : '', 190),
        'college' => je_ai_clean(isset($input['college']) ? $input['college'] : '', 190),
        'current_year' => je_ai_clean(isset($input['current_year']) ? $input['current_year'] : '', 80),
        'city' => je_ai_clean(isset($input['city']) ? $input['city'] : '', 120),
        'preferred_branch' => je_ai_clean(isset($input['preferred_branch']) ? $input['preferred_branch'] : '', 160),
        'learning_mode' => je_ai_clean(isset($input['learning_mode']) ? $input['learning_mode'] : '', 40),
        'preferred_batch' => je_ai_clean(isset($input['preferred_batch']) ? $input['preferred_batch'] : '', 120),
        'message' => je_ai_clean(isset($input['message']) ? $input['message'] : '', 2000),
        'source' => je_ai_clean(isset($input['source']) ? $input['source'] : 'AI_CHAT', 60) ?: 'AI_CHAT',
        'page_url' => je_ai_clean(isset($input['page_url']) ? $input['page_url'] : '', 2000),
        'referrer' => je_ai_clean(isset($input['referrer']) ? $input['referrer'] : '', 2000),
        'utm_source' => je_ai_clean(isset($input['utm_source']) ? $input['utm_source'] : '', 190),
        'utm_medium' => je_ai_clean(isset($input['utm_medium']) ? $input['utm_medium'] : '', 190),
        'utm_campaign' => je_ai_clean(isset($input['utm_campaign']) ? $input['utm_campaign'] : '', 190),
        'utm_term' => je_ai_clean(isset($input['utm_term']) ? $input['utm_term'] : '', 190),
        'utm_content' => je_ai_clean(isset($input['utm_content']) ? $input['utm_content'] : '', 190),
        'device' => je_ai_clean(isset($input['device']) ? $input['device'] : '', 255),
        'conversation_json' => json_encode($safeConversation, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
        'status' => 'new',
    ];
}

function je_ai_append_fallback(array $lead)
{
    $dir = je_ai_root() . '/storage';
    if (!is_dir($dir) && !@mkdir($dir, 0750, true) && !is_dir($dir)) {
        return false;
    }

    $record = $lead;
    $record['_stored_at'] = gmdate('c');
    $record['_storage'] = 'jsonl';
    $line = json_encode($record, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    if ($line === false) {
        return false;
    }

    $file = $dir . '/ai-leads-' . date('Y-m') . '.jsonl';
    return @file_put_contents($file, $line . PHP_EOL, FILE_APPEND | LOCK_EX) !== false;
}

function je_ai_insert_lead(PDO $pdo, array $lead)
{
    $fields = [
        'session_id', 'name', 'mobile', 'email', 'interested_course', 'qualification', 'college',
        'current_year', 'city', 'preferred_branch', 'learning_mode', 'preferred_batch', 'message',
        'source', 'page_url', 'referrer', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_term',
        'utm_content', 'device', 'conversation_json', 'status'
    ];
    $quoted = array_map(function ($field) { return '`' . $field . '`'; }, $fields);
    $placeholders = array_map(function ($field) { return ':' . $field; }, $fields);
    $sql = 'INSERT INTO `je_leads` (' . implode(',', $quoted) . ') VALUES (' . implode(',', $placeholders) . ')';
    $stmt = $pdo->prepare($sql);
    foreach ($fields as $field) {
        $stmt->bindValue(':' . $field, isset($lead[$field]) ? $lead[$field] : null);
    }
    $stmt->execute();
    return (int)$pdo->lastInsertId();
}

function je_ai_store_lead(array $input)
{
    $lead = je_ai_normalize_lead($input);
    if ($lead['name'] === '' || $lead['mobile'] === '') {
        throw new InvalidArgumentException('Name and mobile number are required.');
    }
    if ($lead['email'] !== '' && !filter_var($lead['email'], FILTER_VALIDATE_EMAIL)) {
        throw new InvalidArgumentException('Please enter a valid email address.');
    }
    $digits = preg_replace('/\D+/', '', $lead['mobile']);
    if (strlen($digits) < 8 || strlen($digits) > 15) {
        throw new InvalidArgumentException('Please enter a valid mobile number.');
    }

    // Keep a protected JSONL copy as a fail-safe even when MySQL works.
    $fileSaved = je_ai_append_fallback($lead);
    $dbSaved = false;
    $leadId = null;
    $dbError = null;

    try {
        $db = je_ai_runtime_config('database');
        if (!empty($db)) {
            $pdo = je_ai_db($db);
            je_ai_install_schema($pdo);
            $leadId = je_ai_insert_lead($pdo, $lead);
            $dbSaved = true;
        }
    } catch (Throwable $e) {
        $dbError = $e->getMessage();
    }

    if (!$fileSaved && !$dbSaved) {
        throw new RuntimeException('Lead storage is not available. Please contact the institute directly.');
    }

    $mail = je_ai_runtime_config('mail');
    $mailSent = false;
    if (!empty($mail['enabled']) && !empty($mail['notify_email'])) {
        $subject = 'New website AI lead - ' . ($lead['interested_course'] ?: 'Course enquiry');
        $body = "New Jaipur Engineers website enquiry\n\n"
            . "Name: {$lead['name']}\nMobile: {$lead['mobile']}\nEmail: {$lead['email']}\n"
            . "Course: {$lead['interested_course']}\nQualification: {$lead['qualification']}\n"
            . "City: {$lead['city']}\nMode: {$lead['learning_mode']}\nBatch: {$lead['preferred_batch']}\n"
            . "Message: {$lead['message']}\nSource: {$lead['source']}\nPage: {$lead['page_url']}\n";
        $mailError = '';
        $mailSent = je_ai_send_mail($mail, $mail['notify_email'], $subject, $body, $mailError);
    }

    return [
        'lead_id' => $leadId,
        'database_saved' => $dbSaved,
        'fallback_saved' => $fileSaved,
        'mail_sent' => $mailSent,
        'database_error' => $dbError,
    ];
}

function je_ai_rate_limited($key, $limit = 6, $windowSeconds = 600)
{
    $dir = je_ai_root() . '/storage/rate-limit';
    if (!is_dir($dir)) {
        @mkdir($dir, 0750, true);
    }
    if (!is_dir($dir) || !is_writable($dir)) {
        return false;
    }

    $file = $dir . '/' . hash('sha256', (string)$key) . '.json';
    $now = time();
    $data = ['started' => $now, 'count' => 0];
    if (is_file($file)) {
        $raw = @file_get_contents($file);
        $saved = json_decode((string)$raw, true);
        if (is_array($saved) && isset($saved['started'], $saved['count'])) {
            $data = $saved;
        }
    }
    if (($now - (int)$data['started']) >= $windowSeconds) {
        $data = ['started' => $now, 'count' => 0];
    }
    $data['count'] = (int)$data['count'] + 1;
    @file_put_contents($file, json_encode($data), LOCK_EX);
    return $data['count'] > $limit;
}

function je_ai_smtp_read($socket)
{
    $response = '';
    while (!feof($socket)) {
        $line = fgets($socket, 515);
        if ($line === false) {
            break;
        }
        $response .= $line;
        if (strlen($line) >= 4 && $line[3] === ' ') {
            break;
        }
    }
    return $response;
}

function je_ai_smtp_command($socket, $command, array $expected)
{
    if ($command !== '') {
        fwrite($socket, $command . "\r\n");
    }
    $response = je_ai_smtp_read($socket);
    $code = (int)substr($response, 0, 3);
    if (!in_array($code, $expected, true)) {
        throw new RuntimeException('SMTP error ' . $code . ': ' . trim($response));
    }
    return $response;
}

function je_ai_send_mail(array $settings, $to, $subject, $body, &$error = '')
{
    $error = '';
    $to = trim((string)$to);
    if (!filter_var($to, FILTER_VALIDATE_EMAIL)) {
        $error = 'Invalid recipient email.';
        return false;
    }

    $driver = !empty($settings['driver']) ? strtolower((string)$settings['driver']) : 'smtp';
    $fromEmail = !empty($settings['from_email']) ? trim((string)$settings['from_email']) : '';
    $fromName = !empty($settings['from_name']) ? trim((string)$settings['from_name']) : 'Jaipur Engineers';
    if (!filter_var($fromEmail, FILTER_VALIDATE_EMAIL)) {
        $error = 'Invalid From email.';
        return false;
    }

    $subject = str_replace(["\r", "\n"], '', (string)$subject);
    $safeFromName = str_replace(["\r", "\n"], '', $fromName);

    if ($driver === 'mail') {
        $headers = "From: {$safeFromName} <{$fromEmail}>\r\n";
        $headers .= "Reply-To: {$fromEmail}\r\n";
        $headers .= "Content-Type: text/plain; charset=UTF-8\r\n";
        $ok = @mail($to, $subject, $body, $headers);
        if (!$ok) {
            $error = 'PHP mail() returned false.';
        }
        return $ok;
    }

    try {
        $host = isset($settings['host']) ? trim((string)$settings['host']) : '';
        $port = isset($settings['port']) ? (int)$settings['port'] : 587;
        $encryption = isset($settings['encryption']) ? strtolower((string)$settings['encryption']) : 'tls';
        $username = isset($settings['username']) ? (string)$settings['username'] : '';
        $password = isset($settings['password']) ? (string)$settings['password'] : '';
        if ($host === '' || $port < 1 || $port > 65535) {
            throw new RuntimeException('SMTP host or port is invalid.');
        }

        $remote = ($encryption === 'ssl' ? 'ssl://' : 'tcp://') . $host . ':' . $port;
        $errno = 0;
        $errstr = '';
        $socket = @stream_socket_client($remote, $errno, $errstr, 15, STREAM_CLIENT_CONNECT);
        if (!$socket) {
            throw new RuntimeException('SMTP connection failed: ' . $errstr . ' (' . $errno . ')');
        }
        stream_set_timeout($socket, 15);
        je_ai_smtp_command($socket, '', [220]);
        $ehloHost = isset($_SERVER['SERVER_NAME']) ? preg_replace('/[^a-zA-Z0-9.\-]/', '', $_SERVER['SERVER_NAME']) : 'localhost';
        je_ai_smtp_command($socket, 'EHLO ' . ($ehloHost ?: 'localhost'), [250]);

        if ($encryption === 'tls') {
            je_ai_smtp_command($socket, 'STARTTLS', [220]);
            $cryptoOk = @stream_socket_enable_crypto($socket, true, STREAM_CRYPTO_METHOD_TLS_CLIENT);
            if ($cryptoOk !== true) {
                throw new RuntimeException('Could not enable TLS encryption.');
            }
            je_ai_smtp_command($socket, 'EHLO ' . ($ehloHost ?: 'localhost'), [250]);
        }

        if ($username !== '') {
            je_ai_smtp_command($socket, 'AUTH LOGIN', [334]);
            je_ai_smtp_command($socket, base64_encode($username), [334]);
            je_ai_smtp_command($socket, base64_encode($password), [235]);
        }

        je_ai_smtp_command($socket, 'MAIL FROM:<' . $fromEmail . '>', [250]);
        je_ai_smtp_command($socket, 'RCPT TO:<' . $to . '>', [250, 251]);
        je_ai_smtp_command($socket, 'DATA', [354]);

        $message = 'Date: ' . date(DATE_RFC2822) . "\r\n";
        $message .= 'From: ' . $safeFromName . ' <' . $fromEmail . ">\r\n";
        $message .= 'To: <' . $to . ">\r\n";
        $message .= 'Subject: ' . $subject . "\r\n";
        $message .= "MIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\n";
        $message .= "Content-Transfer-Encoding: 8bit\r\n\r\n";
        $normalizedBody = preg_replace("/\r\n|\r|\n/", "\r\n", (string)$body);
        $normalizedBody = preg_replace('/^\./m', '..', $normalizedBody);
        $message .= $normalizedBody . "\r\n.";
        je_ai_smtp_command($socket, $message, [250]);
        @fwrite($socket, "QUIT\r\n");
        @fclose($socket);
        return true;
    } catch (Throwable $e) {
        $error = $e->getMessage();
        if (isset($socket) && is_resource($socket)) {
            @fclose($socket);
        }
        return false;
    }
}
